server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/selierlin/SpringCloudConfig #GitHub上面的git仓库名字
#          search-paths: sub/son/  # 通过模式匹配来检索子目录sub下的配置文件
